from typing import Final

CMD_EMPTY_RECYCLE_BIN: Final = "Очисти корзину"
CMD_SCREENSHOT: Final = "Сделай скриншот"
CMD_SHUTDOWN: Final = "Выключи компьютер"
CMD_WIFI: Final = "Wi-fi"
CMD_NOTIFICATIONS: Final = "Уведомления"
CMD_AIRPLANE: Final = "Режим полёта"
CMD_BLUETOOTH: Final = "Bluetooth"
CMD_SOUND: Final = "Звук"
CMD_ENERGY_SAVER_ON: Final = "Включи энергосбережение"
CMD_ENERGY_SAVER_OFF: Final = "Выключи энергосбережение"
CMD_RECORD_ON: Final = "Включи запись экрана"
CMD_RECORD_OFF: Final = "Выключи запись экрана"
CMD_LAUNCH_APP: Final = "Открой приложение"
CMD_CLOSE_APP: Final = "Закрой приложение"
CMD_UNINSTALL_APP: Final = "Удали приложение"
CMD_CREATE_FILE: Final = "Создай файл"
CMD_CREATE_FOLDER: Final = "Создай папку"
CMD_DELETE: Final = "Удали"
CMD_RENAME: Final = "Переименуй"
CMD_RUN_SCRIPT: Final = "Запусти скрипт"
CMD_OPEN_SITE: Final = "Открой сайт"
